### ISSUE TITLE
Build form field alignment options

### ISSUE THREAD

**Issue by fynnfeldpausch** [haiilo/catalyst#116]
As of now, inputs and other form elements can have a label set via an input. This label is rendered above the input and is automatically linked to the input via the HTML `for` attribute. However, we do need the possibility to align the label and form elements next to one another.

In a first implementation we added the possibility to set an identifier for the (wrapped native) form element, to allow "external" labels to be used. This comes with its own set of problems, though. Unfortunately, the HTML `for` attribute is not able to pierce the ShadowDOM and is thus not linked to its counterpart. There are various hacks and workarounds for it but none of them really work. The only solution is to wait for StencilJS to implement the newly suggested `attachInternals` to make custom web components behave like native form elements.

Hence, the idea was born to implement the horizontal design as an additional option in the entire component. This allows for the label to still be rendered within the ShadowDOM and resolves those issues. This ticket is about exactly this requirement.

**Acceptance criteria:**
* each form element has an option to align the label horizontally or vertically (vertical being the default)
* alignment options can also be set globally from the wrapping form group (see the optional display option)
* the ratio of label to form input can somehow be configured both directly on the form elements as well as globally via the wrapping form element. This way, we allow for all form elements to have the same alignment.
* documentation for all of this is added to zeroheight.

**Comment by emmoldovan** [comment]
#132

**Comment by fynnfeldpausch** [comment]
Double check the current options with
- select
- checkbox / radio / toggle
