### ISSUE TITLE
Fix tooltip alignment

### ISSUE THREAD

**Issue by fynnfeldpausch** [haiilo/catalyst#124]
**Ref.:** https://haiilo.atlassian.net/browse/TSP-162

Tooltips are misaligned if they are placed in a small container. It seems that the container somehow affects the positioning or sizing of the tooltip. Goal of this ticket is to find the exact root cause of this behaviour and fix it. Details can be found in the linked ticket.

One idea might be to not place the tooltip content within the web component itself, but to clone the content every time when the tooltip is shown and place it directly in the HTML body. This way, we make sure, that the placement is independent from the parent element.

**Comment by emmoldovan** [comment]
#142
