### ISSUE TITLE
Show character limit count on input fields / text areas (maybe?)

### ISSUE THREAD

**Issue by ddoe8** [haiilo/catalyst#136]
There's a need for having the character count of input fields in some of the inputs in use in stories. Currently this is not provided by Catalyst.

Dependent ticket: HSCDB-344

**Comment by mrkskmn** [comment]
Input fields shall receive the option to display their maximum length of characters within their components' UI.
This should be done by having a common dynamic element, displaying X/Y (X characters out of Y total).

The character count is attached to the label of the input and is available for normal labels, as well as external ones.

Please see the design specifications for implementation details.
https://www.figma.com/file/Uflyvg0Ei23C4iIlC4c97X/(Catalyst)-Web?node-id=2854%3A7651&t=S75KDkBTwZmvYDms-11

**Comment by ddoe8** [comment]
Hello, was implementing the change on a HSCDB ticket and noticed a difference in behavior that might be a bug

<img width="390" alt="Screenshot 2023-02-22 at 11 45 41" src="https://user-images.githubusercontent.com/22096243/220598016-e6f28899-5ed9-4126-a9bc-fcd1420235eb.png">

In our use case both fields are required and the char-count moves next to the label, instead of keeping the right side position. For the comparison i made one of the fields non required and that's the result. Same happens on the Catalyst documentation.

Is this a bug or intended behavior?  

@mrkskmn @fynnfeldpausch @emmoldovan FYI

**Comment by emmoldovan** [comment]
I think it is a bug. I am on it

**Comment by emmoldovan** [comment]
#158
