### ISSUE TITLE
cat-select: if I have an item selected the component shows me only that option when opened

### ISSUE THREAD

**Issue by heyhoho** [haiilo/catalyst#146]
when using cat-select without multiple attribute.
populated with [entityA, entityB, entityC]

After user selects entityA in cat-select component.
![CleanShot 2023-02-06 at 17 41 24](https://user-images.githubusercontent.com/124901160/217845694-f05d774e-9dd3-4b01-950d-690d5420e745.png)

The user opens again the component to change the entity to another one, but the cat-select shows only entityA
![CleanShot 2023-02-06 at 17 40 00](https://user-images.githubusercontent.com/124901160/217845701-bb32aa4f-6baa-4cc9-99bc-6328602a8eff.png)

**Comment by emmoldovan** [comment]
#153
