### ISSUE TITLE
Notification Center: Clicking on context menu/ Mark as read button closes the notification center

### ISSUE THREAD

**Issue by sefacoyo** [haiilo/catalyst#152]
1. Activate new navigation bar
2. Go to Notification Center
3. Click context menu or Mark as read button

Actual Result : This action closes the notification center.

Expected Result : Notification center should be stay open.

Jira : https://haiilo.atlassian.net/browse/COYOFOUR-20490

**Comment by emmoldovan** [comment]
The problem in my opinion is that we have 3 situations that we need to solve:

- I want the dropdown to never close until programmatically told so (currently the noAutoClose, i think)
- I want the dropdown to close on outside click (currently that does not work reliably, e.g. with the linked ticket)
- I want to close the dropdown on clicking a button (the default use case of a menu)

**Comment by emmoldovan** [comment]
Try to use (catClick) - event instead of native (click) event when cat-button component is used inside a cat-dropdown

**Comment by klui** [comment]
Thanks for the hint, I will give that a try!

**Comment by klui** [comment]
catClick did the trick.
