### ISSUE TITLE
Fix spacing on single selects using avatars

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#164]
When using the select component as single select and using the avatar prefix, the spacings are off in the selection input.
The avatar should maintain a spacing of 0.5rem to the left edge of the select input.

![CleanShot 2023-02-28 at 10 54 38](https://user-images.githubusercontent.com/98806154/221817756-de956a24-131f-48f2-8d7b-38cc9b47394e.png)

**Comment by emmoldovan** [comment]
#165
