### ISSUE TITLE
Make font-size for xs avatars smaller

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#171]
**Acceptance criteria**
1. The `font-size` for avatars using the size `xs` is changed from `.75rem` to `0.5625rem`

**Comment by fynnfeldpausch** [comment]
Are the fonts sizes too big in general? Because currently all font sizes align with the other specs. If we change this, we have one outlier. Just want to make sure that this is really what we want.

Current implementation (first avatar size, then font size).

```
@include size('xs', 'xs');
@include size('s', 's');
@include size('m', 'm');
@include size('l', 'l');
@include size('xl', 'xl');
```


Variant a?

```
@include size('xs', 0.5625rem);
@include size('s', 'xs');
@include size('m', 's');
@include size('l', 'm');
@include size('xl', 'l');
```


Variant b?

```
@include size('xs', 0.5625rem);
@include size('s', 's');
@include size('m', 'm');
@include size('l', 'l');
@include size('xl', 'xl');
```

**Comment by mrkskmn** [comment]
Thanks for the heads up Fynn. Issue is closed as wont do for now.
