### ISSUE TITLE
Make dropdowns responsive to the viewports dimensions

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#173]
We are encountering issues where dropdowns exceed the available height and clip out of the viewport. This leads to inaccessible dropdown elements. 

**Acceptance criteria**
1. Dropdowns respect the viewport dimensions and do not clip out of their boundaries
2. Dropdowns should maintaining a safe space towards the edge of their viewport
3. The content of a dropdown is scrollable if needed. 

Expected result would be something along the lines of this: 
![CleanShot 2023-03-10 at 15 00 58](https://user-images.githubusercontent.com/98806154/224335653-ae51dc61-cc42-4a86-a617-9b8ec6c9ef76.png)

**Comment by emmoldovan** [comment]
#182
