### ISSUE TITLE
Close dropdown when losing focus

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#174]
When I interact with a nested dropdown, its parent dropdown should stay open. However, when a nested dropdown loses focus by clicking outside of the entire dropdown hierarchy (e.g. opening a different dropdown), it should be closed completely.

**Comment by mrkskmn** [comment]
@fynnfeldpausch feel free to adjust the issue description if mine is faulty/does not make sense.

**Comment by emmoldovan** [comment]
#181
