### ISSUE TITLE
Adjust min clamp on height of the dialogs

### ISSUE THREAD

**Issue by fstbraz** [haiilo/catalyst#179]
Nowadays, we have dialogs with a height smaller than 240px; they have like 164px. 
And when we pass the correct height configuration with `CatDialogConfig`, the min-height clamp overlaps the height configuration. 
It will be nice to have the possibility of having dialogs at a lower height.

![Screenshot 2023-03-13 at 10 40 50](https://user-images.githubusercontent.com/1130728/224966127-abe79ebc-2d31-4272-bf33-8dadc59c89f1.png)

**Comment by ddoe8** [comment]
Any news on this issue?

**Comment by emmoldovan** [comment]
I think it is solved. See this [commit](https://github.com/haiilo/catalyst/commit/5ab48d56a8b2a92c3465997ce124b129afe43be1)

**Comment by ddoe8** [comment]
Okay, nice and it's released in version 5.3.0 right? I guess the ticket can be closed
