### ISSUE TITLE
Remove error logs in tests

### ISSUE THREAD

**Issue by fynnfeldpausch** [haiilo/catalyst#188]
We have quite a few errors in the tests. They dont break them but should be fixed. Its a wrong jest config and we should try to find a general jest setting (probably setting up the mock correctly in the setup-jest function) to fix it:

![Screenshot 2023-03-20 at 11 26 15](https://user-images.githubusercontent.com/1246913/226313382-b9baccfc-2b26-45ec-864a-7d308bae015b.png)

**Comment by emmoldovan** [comment]
#232
