### ISSUE TITLE
Adjust hint styling for checkboxes, radio buttons and toggles

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#204]
We encountered the first real use of hints for checkboxes within the "promotion" feature of comms and need to do some adjustments to the hints.

**Acceptance criteria**
1. Hints are aligned with the label above them
2. Hint use cat-muted as their font color
3. Font size stays the same
4. Line height is adjusted to 1.5

In regards to number 4, we might wanna think about updating the line height for text size s in general to 1.5 / 20px 

Reference screenshot for desired outcome:
![CleanShot 2023-04-13 at 11 53 05](https://user-images.githubusercontent.com/98806154/231724330-bc5b787a-708e-46f3-9412-6479aaf8c5e6.png)

**Comment by emmoldovan** [comment]
#215
