### ISSUE TITLE
Cat badge doesn't support native attributes

### ISSUE THREAD

**Issue by fstbraz** [haiilo/catalyst#210]
Hello, We have a use case where we need to add a test attribute and is currently not support adding it by nativeAttributes 

<img width="620" alt="Screenshot 2023-04-21 at 11 23 47" src="https://user-images.githubusercontent.com/1130728/233613975-92179b24-2ff4-4015-994c-7b458c9ec9a4.png">

**Comment by fynnfeldpausch** [comment]
Can you give an example where this is needed. A badge does not have inner components where we could attach the attributes. In your case, I suggest adding it to the badge directly.
