### ISSUE TITLE
Check potential issues with tooltip used within a dialog box

### ISSUE THREAD

**Issue by andrei-colta-haiilo** [haiilo/catalyst#218]
In the case of the Analytics page in stories-frontend, there is a spacing issue with the tooltips used within a dialog 
![image](https://user-images.githubusercontent.com/132678432/236472285-1c735001-0ff2-44a5-9e34-b6226e28db51.png)

Please check if this is related to how the positioning is determined within catalyst, or some other parts need to be checked

**Comment by emmoldovan** [comment]
Not a catalyst issue, it is a storie frontend implementation issue
