### ISSUE TITLE
catNotificationService displayed wrong in context of admin area

### ISSUE THREAD

**Issue by marcushohlbein** [haiilo/catalyst#241]
the toast/notification isn't display right. it's kind of stacked to the top and behind the content without styling.

![Bildschirmfoto 2023-06-05 um 14 17 35](https://github.com/haiilo/catalyst/assets/21499846/3a8f133b-06b9-4714-9545-d72a8dbeab39)

**Comment by fynnfeldpausch** [comment]
@marcushohlbein Can you provide more info? Where exactly? Steps to reproduce? Which environment

**Comment by marcushohlbein** [comment]
@fynnfeldpausch I tried to implement the notifications inside the Comms Admin MFE, and for public-uat it's not working.

**Reproduce:**

check out my branch PMI-1012 and submit the form. (🚨 **_please use the right credentials!!_**)

**Comment by fynnfeldpausch** [comment]
This is because Catalyst relies on global styles to be set up. Those are not loaded correctly in the Admin area, as Catalyst is not set up in the admin area (AFAIK). Please create a Comms ticket to setup Catalyst in the Admin area.
