### ISSUE TITLE
cat-select component closing after we click to open the cat-dropdown

### ISSUE THREAD

**Issue by fstbraz** [haiilo/catalyst#244]
**Description**: When opening the dropdown and clicking to open the list contained in a cat dropdown, the dropdown automatically disappears, and I can’t choose what I want to select.

**Correct behavior**: The list  should remain open, giving me the option of choosing something from the list without the need to write anything in the search field of the dropdown or reopen the dropdown 

![screen_record](https://github.com/haiilo/catalyst/assets/1130728/cbbf7ada-8d73-4afc-afbb-155b749433e2)

**Comment by emmoldovan** [comment]
#269
