### ISSUE TITLE
Form binding with cat-datepicker is not working properly

### ISSUE THREAD

**Issue by Jeff1899** [haiilo/catalyst#294]
I've discovered an issue where the datepicker is only binding in one direction to the associated form. Specifically, the datepicker binds to the form when a user manually selects a date using the datepicker interface. However, if the date is programmatically set or removed from the form via code, these changes are not reflected in the datepicker.

**Comment by Jeff1899** [comment]
Little bit unsure, if its the right approch to solve this bug, but via the watcher is was the only way I could react to the changes bye a form

**Comment by fynnfeldpausch** [comment]
@Jeff1899 is this still a problem?
