### ISSUE TITLE
Cat-select is losing its option list after selecting an option by pressing the TAB key and than clearing the selection

### ISSUE THREAD

**Issue by emmoldovan** [haiilo/catalyst#296]
Steps to reproduce:

1. Navigate through the select options with arrow keys
2. Select an option by presing tab key
3. Clear selection by pressing the clear icon

https://github.com/haiilo/catalyst/assets/89849556/9f79f9c3-8cd1-4e5c-a3b1-56d739f6e27d

**Comment by emmoldovan** [comment]
#314

**Comment by fynnfeldpausch** [comment]
Again, can also not reproduce it. Lets do this in the daily as well

**Comment by fynnfeldpausch** [comment]
As this was not reproducable earlier today, please take a look again and try to find steps to reproduce @emmoldovan

**Comment by emmoldovan** [comment]
You can reproduce it only in Angular context
1. Start Angular Demo
2. Select on option
3. Blur the select
4. Open again the select options
5. Press clear when the list is still open

Actual results:
- The list is empty

Expected results:
- The list should be populated with options
