### ISSUE TITLE
Catalyst Date Picker is not usable via Keyboard

### ISSUE THREAD

**Issue by HJanecke** [haiilo/catalyst#301]
We use the new catalyst component at the date picker for the archiving assistant at blog articles.
But it is not A11y conform as you can't use the date picker via keyboard.

**Comment by mrkskmn** [comment]
@HJanecke You instantly closed this issue. Is the issue fixed or did you find another solution?

**Comment by HJanecke** [comment]
@mrkskmn I looked at the https://design.haiilo.com/ site and it works, so I assumed for the time being that it wasn't catalyst. But Jeff said that there are several problems that come together and it probably needs to be fixed in the library.
He'll take care of it and create a new ticket if he knows exactly what's going wrong.
Thanks for asking!
