### ISSUE TITLE
Missing ellipsis for cat-input

### ISSUE THREAD

**Issue by therobertmaftei** [haiilo/catalyst#304]
**Steps to reproduce:**
1. add a very long text in cat-input

**Current behavior:**
> no ellipsis at the end
> <img width="404" alt="image" src="https://github.com/haiilo/catalyst/assets/22702708/ae2c7990-d14d-46aa-b4b1-162b7b261b62">

**Expected result:**
> ellipsis should be present at the end of the string to indicate there's more
> <img width="404" alt="image" src="https://github.com/haiilo/catalyst/assets/22702708/aa338d70-1c01-4d6c-a985-a89884eee1fd">

**Comment by mrkskmn** [comment]
@fynnfeldpausch Here's a good example of how it should work. In case you don't know how to proceed here.
https://www.codeply.com/go/xyUMETlNgs
