### ISSUE TITLE
cat-select: Search not working with existing search term

### ISSUE THREAD

**Issue by fynnfeldpausch** [haiilo/catalyst#319]
**Steps to reproduce:**
* click into the select
* search for a term without selecting one
* close the select by clicking outside
* click into the select again to reopen it

**Actual:**
* Search opens without applying the search term

**Expected:**
* Search opens and applies the existing search term for the search

**Comment by emmoldovan** [comment]
I think this was fixed on the following branch fix/cat-select-options. Try to reproduce it there
