### ISSUE TITLE
Asset token: Incorporate twemoji emoji set as default

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#320]
Can we easily incorporate twemoji as emoji font so we can (finally) achieve unified emoji rendering across platforms?

**Comment by fynnfeldpausch** [comment]
This should be possible. But in theory you dont even need  change here anymore. Catalyst allows custom emoji fonts via configuration. We just need twemoji as font.

**Comment by fynnfeldpausch** [comment]
not planned
