### ISSUE TITLE
Set initial value on cat-select

### ISSUE THREAD

**Issue by klui** [haiilo/catalyst#345]
I would like to set an initial value on a cat-select element.
How is this possible?
I already tried setting `value` property to the respective item id before or after calling the `connect`, as well as setting the connected formControl value.
All results in the first option being selected and shown, but not the actual needed one.
This this a bug, not implemented yet, or am I doing something wrong?

**Comment by fynnfeldpausch** [comment]
Thanks for reporting this @klui . I will look into it asap
