### ISSUE TITLE
cat-select: Selection with image is broken

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#347]
<img width="396" alt="CleanShot 2023-08-10 at 14 42 02@2x" src="https://github.com/haiilo/catalyst/assets/98806154/262bf5e7-fe05-4fca-8452-d2f8c95348d8">

**Comment by fynnfeldpausch** [comment]
@mrkskmn where is this coming from? I am not able to reproduce it

**Comment by mrkskmn** [comment]
I saw it in the documentation. But now it is gone. Weird 🤷‍♂️ 
I guess we can close this now as I cannot reproduce it myself anymore.
