### ISSUE TITLE
Icons are not rendered inside documentation

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#348]
Most of the icons are not rendered anymore at design.haiilo.com 
Noticed this across several pages, especially on the icon documentation page: 
https://design.haiilo.com/7a807c8eb/p/097526-icons/b/69f7f9

**Comment by fynnfeldpausch** [comment]
@mrkskmn it is not working for no reason in the deprecated code view. seems we need to convert all code view to the new one now :-/

**Comment by mrkskmn** [comment]
Updated all old code blocks to new ones.
