### ISSUE TITLE
cat-input: Hint slot is still rendered when hidden

### ISSUE THREAD

**Issue by mrkskmn** [haiilo/catalyst#395]
Same issue we had a while ago for the hint slot. 
https://github.com/haiilo/catalyst/issues/328

When the hint slot is not in use, we still render it inside the DOM. This breaks the spacings as the flex gap is applied. 
Elements which are not used should also not be rendered. This might also apply for cat-textarea.

![CleanShot 2023-10-09 at 12 59 02@2x](https://github.com/haiilo/catalyst/assets/98806154/bc45cb12-f8c8-4502-8626-36a60d5becec)

**Comment by fynnfeldpausch** [comment]
cannot reproduce
