### ISSUE TITLE
cat-radio: not possible to set a boolean value

### ISSUE THREAD

**Issue by malikov917** [haiilo/catalyst#400]
**Steps to reproduce:**

1. create cat-radio-group using reactive angular forms
2. create 2 cat-radio elements with boolean values as [value]="true" and [value]="false"
3. try to interact with the element

**Actual result:** 
Both radio elements are checked (active)

**Expected result:** 
Only selected element is active after it's clicked, and the rest elements are incactive

This html is just a raw example to be sure we're on the same page:
```html
          <cat-radio-group formControlName="publishAsAuthor">
            <cat-radio [value]="false">
              <span slot="label">
                {{'APP.BLOG.ARTICLE.PUBLISH_AS_SENDER' | translate }}
                <strong>({{sender.displayName}})</strong>
              </span>
            </cat-radio>
            <cat-radio *ngIf="currentUser$ | async; let currentUser" [value]="true">
              <span slot="label">
                {{'APP.BLOG.ARTICLE.PUBLISH_AS_AUTHOR' | translate }}
                <strong>
                  ({{blogArticle.originalAuthorName ? blogArticle.originalAuthorName : currentUser.displayName}})
                </strong>
              </span>
            </cat-radio>
          </cat-radio-group>
```

**Comment by fynnfeldpausch** [comment]
I think you are using the radioGroup in a wrong way

1. with reactive forms you dont set the value in the template but in the controller
2. the value should be unique and correspond to the value of the form value accessor

you could for example use the IDs of the user and sender.

**Comment by malikov917** [comment]
thanks, we will try out @fynnfeldpausch

**Comment by pixartist** [comment]
In the case the form value accessor represents a boolean, thus  it's correct to have a true and a false radio box. Also you can't really set the values for each radio button afaik as radio's typically have static values that represent the space of possible values of that accessor

**Comment by fynnfeldpausch** [comment]
Radio buttons only support string values, no booleans

**Comment by finnfabians** [comment]
Hey I think this issue was misdiagnosed. As far as I can see, boolean value actually DO work. The issue here was that one of the radio boxes was conditional with an async pipe and this added in a later frame which is apparently causing the cat-radio-group to entirely fail.
