### ISSUE TITLE
valueChanges observable stops emitting after an input contained a valid value

### ISSUE THREAD

**Issue by finnfabians** [haiilo/catalyst#412]
The valueChanged observable of a text input will only emit until the validation for that field is successful once.

**Comment by fynnfeldpausch** [comment]
@finnfabians Please provide a code example. I am not able to reproduce the error.  Everything works as expected.

**Comment by finnfabians** [comment]
That is strange. I did not test this under isolated conditions so it might be some side effect. If it does not generally occur, I guess we can ignore it for now.

**Comment by fynnfeldpausch** [comment]
Ok, let's reopen it, when it comes up again.
