### ISSUE TITLE
cat-datepicker is not aligned on the text baseline

### ISSUE THREAD

**Issue by finnfabians** [haiilo/catalyst#426]
Instead it is aligned on the top of the input

**Comment by fynnfeldpausch** [comment]
a bit mor info and a screenshot would be very helpful

**Comment by finnfabians** [comment]
how it should be: 
<img width="573" alt="image" src="https://github.com/haiilo/catalyst/assets/101651030/e746311e-8b4c-4727-b7f5-d46c064cce7f">

How it currently is: 
<img width="588" alt="image" src="https://github.com/haiilo/catalyst/assets/101651030/8c431123-6b20-4874-96ec-6850b58ef28f">
