### ISSUE TITLE
Datepicker state inconsistency in chrome

### ISSUE THREAD

**Issue by finnfabians** [haiilo/catalyst#427]
When manually typing a time into the datepicker, the value will only be applied when pressing enter. When leaving the text-field by clicking somewhere else (blur), the value will visually remain but the internal value of the component will not change. The value may also revert visually when the value is read from the form by the component (e.g. on submit).

**Comment by fynnfeldpausch** [comment]
If the value is valid, would you expect it to be applied on blur (without enter) or reverted? @mrkskmn any thoughts?

**Comment by JonayLo** [comment]
Hi @fynnfeldpausch , any news on that? IMO if date is valid it should applied right away on blur
