### ISSUE TITLE
Date picker accessibility: Choose/Change date and closing dialog via keyboard

### ISSUE THREAD

**Issue by denise-hertwig** [haiilo/catalyst#437]
As a user, I want to use the datepicker via keyboard. 

- Choosing a date with keyboard should be possible
- Choosing a date range with keyboard should be possible
- Change date with keyboard should be possible
- Close datepicker with keyboard should be possible

**Comment by denise-hertwig** [comment]
Jira Ticket:https://haiilo.atlassian.net/browse/COYOFOUR-21893

**Comment by glushkova91** [comment]
Duplicate of #310. After short investigation I can say that flatpickr library doesn't allow keyboard navigation if `allowInput` config is on(and in catalyst this flag is always true).
