### ISSUE TITLE
Cat-datepicker the weekday labels are confusing

### ISSUE THREAD

**Issue by geralrodrigues** [haiilo/catalyst#438]
The weekday labels are wrong

**Actual result:** 
Sun Fri Sat Sun Mon Tue Wed
**Expected result:**
Sun Mon Tue Wed Thu Fri Sat

![image](https://github.com/haiilo/catalyst/assets/100929087/c1efd652-575d-4aee-b64f-8801840758b3)

**Comment by fynnfeldpausch** [comment]
I thought I fixed this one recently
