### ISSUE TITLE
Cat-datepicker: Flatpickr library is not maintained anymore

### ISSUE THREAD

**Issue by glushkova91** [haiilo/catalyst#464]
We use Flatpickr[https://www.npmjs.com/package/flatpickr](url) for datepicker component which has not been updated for last 2 years and has 662 open issues. One of the open issues is about wrong position calculation when we append calendar to element instead of body using `appendTo` (https://github.com/flatpickr/flatpickr/issues/1619)
I found a workaround for that using @floating-ui/dom: https://github.com/haiilo/catalyst/pull/462.
But I'd consider replacing Flatpickr with another better supported library.

**Comment by fynnfeldpausch** [comment]
@glushkova91 do you have any (accessible!) alternative in mind?

**Comment by fynnfeldpausch** [comment]
What about https://air-datepicker.com/ ?
