### ISSUE TITLE
Tooltip for menu items reappears after closing the popover that the menu item is connected to

### ISSUE THREAD

**Issue by FreekGille** [haiilo/catalyst#517]
**Steps to reproduce**
1. Open the Notification Center by clicking on the notification icon.
2. Click on a notification (or click just outside the Notification popup to close it).

**Actual result**
The tooltip for “Notifications” reappears even if I don't hover over it. It disappears when clicking anywhere.

**Expected result**
The tooltip shouldn't be visible if not being hovered over.

The issue is not exclusive to Notifications and also appears when using the new Quick Launchpad.
Can be reproduced on the current version (45.0.432) but on 45.0.380 it can’t be reproduced and works as expected.

See JIRA ticket: https://haiilo.atlassian.net/browse/COYOFOUR-22645

**Comment by glushkova91** [comment]
it looks like `setReturnFocus` fault(though it just works as intended).
