### ISSUE TITLE
Pasting several entries to a cat-select w/ multiple and tags enabled does not create tags.

### ISSUE THREAD

**Issue by ddoe8** [haiilo/catalyst#585]
While working on invite external users dialog migration, [here](https://haiilo.atlassian.net/browse/COYOFOUR-23258), we came across the need to paste a list of emails, have them validated and allow admins to invite those users to a community. We were able to find a solution for this, but it seems from Catalyst, the individual "tags" are not created for each email entry. Instead we just get one single tag with all the emails that were pasted.

PR for reference: https://gitlab.com/coyoapp/csi/coyo/-/merge_requests/12042

Change that was not implemented that would process the list of pasted emails:
`ngOnInit(): void {
    this.form.get('emails')?.valueChanges.subscribe(value => {
      console.log('value: ', value);
      if (value?.tags?.length === 1) {
        const emails = value.tags[0].split(/[\s,;]+/).filter((email: string) => email.length > 0);
        this.form.get('emails')?.setValue({ tags: emails }, { emitEvent: false });
        console.log('emails: ', emails);
        console.log('form value tags: ', 'form: ', this.form?.value?.emails?.tags);
      } else if (value?.tags?.length === 0) {
        this.form.get('emails')?.setValue(null, { emitEvent: false });
      }
    });
  }`
  
  Alternatively we could also think about extending the input component to somehow cover this use case!

**Comment by glushkova91** [comment]
the ticket can be closed since cat-tags was implemented, so no changes is cat-select is needed anymore
