### ISSUE TITLE
Feedback: I expect the calendar popup to open in cat-date when clicking anywhere in the input field

### ISSUE THREAD

**Issue by FreekGille** [haiilo/catalyst#615]
As a user, I've been confused by the behavior of cat-date that only clicking on the calendar icon opens the calendar popup while clicking on the input field just allows me to type. I would expect the calendar popup to open in both scenarios, similar to how the old datepicker worked.

**Comment by fynnfeldpausch** [comment]
This has been discussed and there are several concerns regarding accessibility with it. Overall the consensus seems to be that it is more accurate to have a dedicated button trigger the dropdown. For now, we will not implement another option.
